name: vnrplacements
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.5+3
  http: ^0.12.0+2
  dio: ^3.0.9
  path_provider: ^1.6.5
  permission: ^0.1.7
  permission_handler: ^5.0.0+hotfix.3
  connectivity: ^0.4.8+6
  fluttertoast: ^4.0.1
  flutter_offline: "^0.3.0"
  url_launcher: ^5.4.10
  open_file: ^3.0.1
  flutter_swiper: ^1.1.6
  app_settings: ^3.0.1
  store_redirect: ^1.0.2
  carousel_slider: ^2.0.0
  flutter_spinkit: ^3.1.0
  marquee: ^1.3.1
  shared_preferences: ^0.5.7+3

  gradient_widgets: ^0.5.2
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

  google_fonts: ^1.0.0
  fancy_bottom_navigation: ^0.3.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/jobnobgc.png"
flutter_native_splash:
  image: images/jobnobga.png
  color: "#FF00BCD4"
  ios: false
