name: vnrplacements
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.5+3
  http: ^0.12.0+2
  flutter_downloader: ^1.4.3
  dio: ^3.0.9
  path_provider: ^1.6.5
  permission: ^0.1.7
  permission_handler: ^5.0.0+hotfix.3
  flutter_local_notifications: ^1.4.1
  progress_dialog: ^1.2.0
  connectivity: ^0.4.8+2
  fluttertoast: ^4.0.1
  flutter_offline: "^0.3.0"
  url_launcher: ^5.4.2
  open_file: ^3.0.1
  snaplist: ^0.1.5
  flutter_swiper: ^1.1.6
  app_settings: ^3.0.1
  store_redirect: ^1.0.2
  flutter_plugin_pdf_viewer: ^1.0.7
  carousel_slider: ^2.0.0
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
